# Markdown showing how to simulate the package assuming Palivizumab and long-acting monoclonal antibody programme only.

## Add economics, risks of the programme

```{r}

# initialize the class
devtools::load_all()
RSVempty <- make_rsv_programme()

# Load the relevant csv files`
econ_raw <- read.csv(file = system.file(package = "rsvie", "extdata", "econ", "econ_pars.csv")) 
risks_raw <- read.csv(file = system.file(package = "rsvie", "extdata", "econ", "outcome_risks.csv"))
risks_vhr_raw <- read.csv(file = system.file(package = "rsvie", "extdata", "econ", "outcome_risks_vhr.csv"))

# Add the economic information to the class
RSVempty <- add_economics(RSVempty, econ_name = "E_W2023", econ_raw, risks_raw, risks_vhr_raw)
plot_economics(RSVempty)
plot_economics_fit(RSVempty)

```


## Add the intervention programme

```{r}

cal_none <- read.csv(file = system.file(package = "rsvie", "extdata", "calendars", "cal_none.csv")) 
cal_vhr_s <- read.csv(file = system.file(package = "rsvie", "extdata", "calendars", "cal_vhr_s.csv")) 
cal_vhr_yr <- read.csv(file = system.file(package = "rsvie", "extdata", "calendars", "cal_vhr_yr.csv")) 

cal_mabs_s <- read.csv(file = system.file(package = "rsvie", "extdata", "calendars", "cal_mabs_s.csv")) 
cal_mabs_s_cu <- read.csv(file = system.file(package = "rsvie", "extdata", "calendars", "cal_mabs_s_cu.csv")) 
cal_mabs_yr <- read.csv(file = system.file(package = "rsvie", "extdata", "calendars", "cal_mabs_yr.csv")) 

disease_eff <- read_rds( here::here("inst", "extdata", "efficacies", "disease_specific.rda"))
efficacy_t <- load(file = system.file(package = "rsvie", "extdata", "efficacies", "nmab_nobound_post_wane.RData")) 
efficacy <- get(efficacy_t)

immune_profile_none <- list(
    mass = list(product = "none"),
    
    vhr = list(
        product = "none"),
    direct = FALSE
)

immune_profile_mab <- list(
    mass = list(
        product = "mab",
        wane_function = "a * exp(b * t))",  a = abs(efficacy$wane_a_er3), b = abs(efficacy$wane_b_er3),
        sero_delay = "none"
    ),
    vhr = list(
        product = "mab",
        wane_function = "a * exp(b * t))", a = abs(efficacy$wane_a_er3), b = abs(efficacy$wane_b_er3),
        sero_delay = "none"
    ),
    direct = FALSE,
    disease_eff = disease_eff
)


RSV_none <- add_programme(RSVempty, prog_name = "none", cal_none, cal_vhr_s, immune_profile_none)
RSV_mab_s <- add_programme(RSVempty, prog_name = "mab_s", cal_mabs_s, cal_vhr_s, immune_profile_mab)
RSV_mab_s_cu <- add_programme(RSVempty, prog_name = "mab_s_cu", cal_mabs_s_cu, cal_vhr_s, immune_profile_mab)
RSV_mab_yr <- add_programme(RSVempty, prog_name = "mab_yr", cal_mabs_yr, cal_vhr_yr, immune_profile_mab)

RSV_none <- rsvie::run(RSV_none)
RSV_mab_s <- rsvie::run(RSV_mab_s)
RSV_mab_s_cu <- rsvie::run(RSV_mab_s_cu)
RSV_mab_yr <- rsvie::run(RSV_mab_yr)

```

## Some sanity checks to make sure everything is working

```{r}

RSV_mab_s_states <- checkout_states(RSV_mab_s)
RSV_mab_s_cu_states <- checkout_states(RSV_mab_s_cu)
RSV_mab_yr_states <- checkout_states(RSV_mab_yr)

######### THINGS TO CHECK OUT ARE SANE IN STATES ###########

RSV_mab_s_states %>% filter(risk_group == "LR", social_group == "n", state_name %in% c("E0", "E1", "E2", "E3")) %>%
    group_by(t, age_group, model_type) %>% summarise(tot_age = sum(incidence)) %>% filter(age_group <= 12) %>%
    ggplot() + geom_line(aes(t, tot_age, color = as.character(age_group))) + facet_grid(vars(model_type))

RSV_mab_s_states %>% filter(risk_group == "LR", social_group == "n", state_name %in% c("I0", "I1")) %>%
    group_by(t, age_group, model_type) %>% summarise(tot_age = sum(incidence)) %>% filter(age_group <= 12) %>%
    ggplot() + geom_line(aes(t, tot_age, color = as.character(age_group))) + facet_grid(vars(model_type))

RSV_mab_s_cu_states %>% filter(risk_group == "LR", social_group == "n", state_name %in% c("I0", "I1", "I2", "I3")) %>%
    group_by(t, age_group, model_type) %>% summarise(tot_age = sum(incidence)) %>% filter(age_group <= 12) %>%
    ggplot() + geom_line(aes(t, tot_age, color = as.character(age_group))) + facet_grid(vars(model_type))

RSV_mab_yr_states %>% filter(risk_group == "LR", social_group == "n", state_name %in% c("I0", "I1", "I2", "I3")) %>%
    group_by(t, age_group, model_type) %>% summarise(tot_age = sum(incidence)) %>% filter(age_group <= 12) %>%
    ggplot() + geom_line(aes(t, tot_age, color = as.character(age_group))) + facet_grid(vars(model_type))

RSV_mab_s_states %>% filter(risk_group == "VHR", social_group == "n", state_name == "V0_mab") %>% 
        filter(age_group <= 12) %>%
        ggplot() + geom_line(aes(t, incidence, color = as.character(age_group))) + facet_grid(vars(model_type))


RSV_mab_s_states %>% filter(risk_group == "LR", social_group == "n", state_name == "V1_mab") %>% 
        filter(age_group <= 12) %>%
        ggplot() + geom_line(aes(t, incidence, color = as.character(age_group))) + facet_grid(vars(model_type))

RSV_mab_s_cu_states %>% filter(risk_group == "LR", social_group == "n",state_name == "V0_mab") %>% 
        filter(age_group <= 12) %>%
        ggplot() + geom_line(aes(t, incidence, color = as.character(age_group))) + facet_grid(vars(model_type))

RSV_mab_yr_states %>% filter(risk_group == "LR", social_group == "n",state_name == "V0_mab") %>% 
        filter(age_group <= 12) %>%
        ggplot() + geom_line(aes(t, incidence, color = as.character(age_group))) + facet_grid(vars(model_type))



######### THINGS TO CHECK OUT ARE SANE IN INCIDENCE ###########
# 3. Incidence 
inci_df_mab_s <- checkout_incidence(RSV_mab_s)
inci_df_mab_s_cu <- checkout_incidence(RSV_mab_s_cu)
inci_df_mab_yr <- checkout_incidence(RSV_mab_yr)

# 3.1 Make sure incidence waves are sensible
inci_df_mab_s %>% filter(incidence > 0) %>%
    ggplot() + 
        geom_line(aes(x = t, y = incidence, color = as.character(age_group))) + 
        facet_grid(vars(risk_group, social_group), scales = "free_y") + theme_bw()

inci_df_mab_s_cu %>% filter(incidence > 0) %>%
    ggplot() + 
        geom_line(aes(x = t, y = incidence, color = as.character(age_group))) + 
        facet_grid(vars(risk_group, social_group), scales = "free_y") + theme_bw()

inci_df_mab_yr %>% filter(incidence > 0) %>%
    ggplot() + 
        geom_line(aes(x = t, y = incidence, color = as.character(age_group))) + 
        facet_grid(vars(risk_group, social_group), scales = "free_y") + theme_bw()




```


```{r}

RSV_none <- rsvie::run(RSV_none)
RSV_mab_s <- rsvie::run(RSV_mab_s)
RSV_mab_s_cu <- rsvie::run(RSV_mab_s_cu)
RSV_mab_yr <- rsvie::run(RSV_mab_yr)

obj_base <- RSV_none
obj_inter <- list(RSV_mab_s, RSV_mab_s_cu, RSV_mab_yr)

compare_mab <- compare_interventions(obj_base, obj_inter)

library(ggdist)

p1 <- compare_mab %>% filter(age_group >= 13) %>%
    ggplot() + 
        stat_pointinterval(aes(age_group, cases, color = type)) + 
        facet_wrap(vars(outcome), scales = "free_y") + 
        theme_bw()

p2 <- compare_mab %>% filter(age_group >= 13) %>%
    ggplot() + 
        stat_pointinterval(aes(age_group, cases_VHR, color = type)) + 
        facet_wrap(vars(outcome), scales = "free_y") + 
        theme_bw()
p1 / p2


p1 <- compare_mab %>% filter(age_group <= 12) %>%
    ggplot() + 
        stat_pointinterval(aes(age_group, cases, color = type)) + 
        facet_wrap(vars(outcome), scales = "free_y") + 
        theme_bw()

p2 <- compare_mab %>% filter(age_group <= 12) %>%
    ggplot() + 
        stat_pointinterval(aes(age_group, cases_VHR, color = type)) + 
        facet_wrap(vars(outcome), scales = "free_y") + 
        theme_bw()
p1 / p2

```