# Markdown showing how to simulate the package assuming no intervention programme.

## Add economics, risks of the programme


```{r}


ParameterValuesforODE <- function(currentParamValues) {
  if(length(currentParamValues) != 25) {
    stop("currentParamValues must have 25 elements.")
  }
  
  parameterValuesTemp <- numeric(25)
  
  names(parameterValuesTemp) <- c("xi", "si", "ga0", "g1", "g2", "om", "pA1", "pA2", "pA3", "pA4", 
                                  "alpha_i", "d1", "d2", "d3", "phi", "qp", "qc", "b1", "psi", 
                                  "c5ep1", "c5ep2", "ep5", "ep6", "I1", "I2")
  
  parameterValuesTemp <- setNames(currentParamValues, names(parameterValuesTemp))
  
  # Define and compute ep_t and pA
  ep_t <- numeric(25)
  pA <- numeric(25)
  parameterValues <- parameterValuesTemp
  
  for (a in 1:16) {
    ep_t[a] <- exp(parameterValues["c5ep1"] + (a - 1) * parameterValues["c5ep2"])
  }
  for (a in 17:23) {
    ep_t[a] <- parameterValues["ep5"]
  }
  for (a in 24:25) {
    ep_t[a] <- parameterValues["ep6"]
  }
  
  pA[1:12] <- rep(parameterValues["pA1"], 12)
  pA[13:16] <- rep(parameterValues["pA2"], 4)
  pA[17:18] <- rep(parameterValues["pA3"], 2)
  pA[19:25] <- rep(parameterValues["pA4"], 7)
  
  assign("ep_t", ep_t, envir = .GlobalEnv)
  assign("pA", pA, envir = .GlobalEnv)
  assign("parameterValues", parameterValues, envir = .GlobalEnv)
  
}

devtools::load_all()

load(here::here("inst/extdata/data-raw/uk_data_sum.RData"))
load(here::here("inst/extdata/data-raw/posteriors.Rda"))

param_means <- colMeans(post)
param_medians <- apply(post, 2, median)


currentParamValues <- param_means
ParameterValuesforODE(currentParamValues)


# generate inital M
ageStratification = uk_data_sum$ageGroupBoundary
ageStratification

populationPerAgeGroup = uk_data_sum$populationAgeGroup
populationPerAgeGroup


initial_M <- function(parameterValues, ageStratification, populationPerAgeGroup) {
    xi <- 1.0 / parameterValues[['xi']]
    
    init_con <- numeric(0)
    
    for (i in 1:(length(ageStratification) - 1)) {
        
        cdf_lower <- pexp((365 * ageStratification[i]), rate = xi)
        cdf_upper <- pexp((365 * ageStratification[i + 1]), rate = xi)
        
        init_con_temp <- (cdf_upper - cdf_lower) / ((365 * ageStratification[i + 1] - 365 * ageStratification[i]) * xi)
        init_con[i] <- init_con_temp * populationPerAgeGroup[i]
    }
    
    cdf_last <- pexp(365 * 90, rate = xi) - pexp(365 * ageStratification[length(ageStratification)], rate = xi)
    last_age_group_init_con <- cdf_last / ((365 * 90 - 365 * ageStratification[length(ageStratification)]) * xi) * populationPerAgeGroup[length(ageStratification)]
    
    init_con <- c(init_con, last_age_group_init_con)
    
    return(init_con)
    }
    ####
    poisson_cdf <- function(l, a, x) {
    if (l == 0.0 || a == 0.0) {
        return(ppois(x, lambda = 0.000001))
    } else {
        return(ppois(x, lambda = l * a))
    }
    }
    ####
    initialProportionExposure <- function(l, a1, a2) {
    
    prop <- vector("numeric", 4)
    prop[1] <- abs(poisson_cdf(l, a2, 0) - poisson_cdf(l, a1, 0)) / ((a2 - a1) * l)
    prop[2] <- abs(poisson_cdf(l, a2, 1) - poisson_cdf(l, a1, 1)) / ((a2 - a1) * l)
    prop[3] <- abs(poisson_cdf(l, a2, 2) - poisson_cdf(l, a1, 2)) / ((a2 - a1) * l)
    prop[4] <- 1 - sum(prop[1:3])
    
    return(prop)
}

initial_M(param_means, ageStratification, populationPerAgeGroup)


````

```{r}

generateInitialStates <- function(cov_c, parameterValues, ageStratification, populationPerAgeGroup) {

  populationMatPro <- initial_M(parameterValues, ageStratification, populationPerAgeGroup)
  
  I1 <- parameterValues[["l1"]]
  I2 <- parameterValues[["l2"]]
  I3 <- 0.5
  si <- 1.0 / parameterValues[["si"]]
  g0 <- 1.0 / parameterValues[["g0"]]
  g1 <- 1.0 / (parameterValues[["g0"]] * parameterValues[["g1"]])
  g2 <- 1.0 / (parameterValues[["g0"]] * parameterValues[["g1"]] * parameterValues[["g2"]])
  d1 <- parameterValues[["d1"]]
  d2 <- parameterValues[["d1"]] * parameterValues[["d2"]]
  d3 <- parameterValues[["d1"]] * parameterValues[["d2"]] * parameterValues[["d3"]]
  
initialStates <- c()
  for (a in 1:25) {
    if (a < 25) {
      a1 <- ageStratification[a]
      a2 <- ageStratification[a + 1]
    } else {
      a1 <- ageStratification[a]
      a2 <- 90
    }
    
    propEachExposureGroup <- initialProportionExposure(I3, a1, a2)  
    pI1 <- propEachExposureGroup[1]
    pI2 <- propEachExposureGroup[2]
    pI3 <- propEachExposureGroup[3]
    pI4 <- propEachExposureGroup[4]
    age_size <- populationPerAgeGroup[a] - populationMatPro[a]
    
    for (s in 0:5) {
      if (a < 12) {
        if (s == 0 || s == 3) {
          s_prop <- 0.0
        } else if (s == 1 || s == 4) {
          s_prop <- cov_c[a]
        } else if (s == 2 || s == 5) {
          s_prop <- 1 - cov_c[a]
        } else {
          stop("OOPS")
        }
      } else {
        if (s == 0 || s == 3) {
          s_prop <- p_mat[a] * (1 - cov_c[a])
        } else if (s == 1 || s == 4) {
          s_prop <- p_mat[a] * cov_c[a]
        } else if (s == 2 || s == 5) {
          s_prop <- 1 - p_mat[a]
        } else {
          stop("OOPS")
        }
      }
      
      for (r in 0:2) {
        if (r == 0) {
          r_prop <- pVHR[a]
        } else if (r == 1) {
          r_prop <- pHR[a]
        } else if (r == 2) {
          r_prop <- pLR[a]
        } else {
          stop("ERROR")}
        
        
        initialStates_i <- c(r_prop * s_prop * populationMatPro[a],  # M group
                           
                           r_prop * s_prop * pI1 * age_size * (1 - I1) * (1 - I2),  # S
                           r_prop * s_prop * pI1 * age_size * I1 * si / (si + g0),  # E
                           r_prop * s_prop * pI1 * age_size * I1 * g0 / (si + g0) * pA[a],  # A
                           r_prop * s_prop * pI1 * age_size * I1 * g0 / (si + g0) * (1 - pA[a]),  # I
                           r_prop * s_prop * pI1 * age_size * (1 - I1) * I2,  # R
                           
                           r_prop * s_prop * pI2 * age_size * (1 - d1 * I1) * (1 - I2),  # S
                           r_prop * s_prop * pI2 * age_size * d1 * I1 * si / (si + g1),  # E
                           r_prop * s_prop * pI2 * age_size * d1 * I1 * g1 / (si + g1) * pA[a],  # A
                           r_prop * s_prop * pI2 * age_size * d1 * I1 * g1 / (si + g1) * (1 - pA[a]),  # I
                           r_prop * s_prop * pI2 * age_size * (1 - d1 * I1) * I2,  # R
                           
                           r_prop*s_prop*pI3*age_size*(1.0 - d2*I1)*(1.0-I2),      # S
                           r_prop*s_prop*pI3*age_size*d2*I1*si/(si+g2),            # E
                           r_prop*s_prop*pI3*age_size*d2*I1*g2/(si+g2)*pA[a],      # A
                           r_prop*s_prop*pI3*age_size*d2*I1*g2/(si+g2)*(1-pA[a]),  # I
                           r_prop*s_prop*pI3*age_size*(1.0 - d2*I1)*I2,      # R
                           
                           r_prop*s_prop*pI4*age_size*(1.0 - d3*I1)*(1.0-I2),        # S
                           r_prop*s_prop*pI4*age_size*d3*I1*si/(si+g2),       # E
                           r_prop*s_prop*pI4*age_size*d3*I1*g2/(si+g2)*pA[a], # A
                           r_prop*s_prop*pI4*age_size*d3*I1*g2/(si+g2)*(1-pA[a]),   # I
                           r_prop*s_prop*pI4*age_size*(1.0 - d3*I1)*I2    # R
        )
         initialStates <- c(initialStates, initialStates_i, rep(0, 24)) # these are vaccine states which are intiially 0
      }
    }
    initialStates <- c(initialStates, rep(0, 23)) # these are summary states for output
  }
  return(initialStates)
}



pVHR <- uk_data_sum$pVHR
pHR <- uk_data_sum$pHR
pLR <- uk_data_sum$pLR
p_mat <- uk_data_sum$prop_mat
cov_c <- uk_data_sum$nmat
initialStates_i <- generateInitialStates(p_mat, param_means, ageStratification, populationPerAgeGroup)






```


```{r}

# Initialize the class
devtools::load_all()
RSVempty <- make_rsv_programme(S = 1) # S is the number of monte carlo simualtions

# Load the relevant csv files (these are given with the package but the user can make their own)
econ_raw <- read.csv(file = system.file(package = "rsvie", "extdata", "econ", "econ_pars.csv")) 
risks_raw <- read.csv(file = system.file(package = "rsvie", "extdata", "econ", "outcome_risks.csv"))
risks_vhr_raw <- read.csv(file = system.file(package = "rsvie", "extdata", "econ", "outcome_risks_vhr.csv"))

RSVempty <- add_economics(RSVempty, econ_name = "E_W2023", econ_raw, risks_raw, risks_vhr_raw)
plot_economics(RSVempty)
plot_economics_fit(RSVempty)

```

## Add the intervention programme

```{r}

# Load a calendar with no intervention 
disease_eff <- read_rds( here::here("inst", "extdata", "efficacies", "disease_specific.rda"))
cal_none <- read.csv(file = system.file(package = "rsvie", "extdata", "calendars", "cal_none.csv")) 

# No intervention programme so define immunological profile like this:
immune_profile_none <- list(
    mass = list(product = "none"),
    vhr = list(product = "none"),
    disease_eff = disease_eff
)

RSV_none <- add_programme(RSVempty, prog_name = "none", cal_none, cal_none, immune_profile_none)
RSV_none <- rsvie::run(RSV_none)

```


## Here are a few snaity checks

```{r}

# run state outputs the state variable at each time step instead of the incidence (it's an enormous file hence why we chose S = 1)
none_test <- rsvie::run_state(RSV_none)
save(none_test,  file = here::here("inst", "extdata", "tests", "state_none_180423.RData") )

df_states <- checkout_states(RSV_none)

######### THINGS TO CHECK OUT ARE SANE ###########
# 1. Population sizes
# 1.1. Summary metrics in the model
df_states %>% filter(state_name %in% c("sum18", "sum19", "sum20", "sum21", "sum22", "sum23" )) %>% 
    filter(incidence > 0) %>%
    ggplot() + geom_line(aes(t, incidence, color = state_name)) + 
    facet_wrap(vars(age_group))
# TICK

# 1.2. dynamics allocation in the groupsRSV_mab_s_65_states %>% filter(risk_group == "VHR", social_group == "n",state_name == "V3_lav") %>% 

df_states %>% filter(risk_group == "LR", social_group == "n", state_name %in% c("I0", "I1", "I2", "I3")) %>%
    group_by(t, age_group) %>% summarise(tot_age = sum(incidence)) %>% filter(age_group <= 12) %>%
    ggplot() + geom_line(aes(t, tot_age, color = as.character(age_group)))
# TICK


# 2. Some arbitrary stuff
df_states_pos <- df_states %>% filter(incidence > 0)
temp_data <- df_states_pos %>% filter(risk_group == "LR", social_group == "n", age_group == 1)

temp_data %>% 
    ggplot() + geom_line(aes(t, incidence, color = state_name)) + 
    facet_grid(vars(model_type))


# 3. Incidence 
inci_df <- checkout_incidence(RSV_none)

# 3.1 Make sure incidence waves are sensible
inci_df %>% filter(incidence > 0) %>%
    ggplot() + 
        geom_line(aes(x = t, y = incidence, color = as.character(age_group))) + 
        facet_grid(vars(risk_group, social_group)) + theme_bw()

inci_df %>% filter(incidence > 0) %>% group_by(age_group, t, risk_group) %>% 
    summarise(incidence = sum(incidence)) %>% filter(age_group < 12) %>%
    ggplot() + 
        geom_line(aes(x = t, y = incidence, color = as.character(age_group))) + 
        facet_grid(vars(risk_group)) + theme_bw()


```